_inputs:
  map:
    comment: Update the map location and display settings.
  latitude:
    comment: Coordinates for the center marker on the map.
  longitude:
    comment: Coordinates for the center marker on the map.
  zoom:
    comment: The zoom level for the map.
  pricing_table:
    comment: Update the information in the pricing tables.
  highlight:
    comment: Emphasis the text
  color:
    comment: The background colour used in the plan name and call to action.
  new_window:
    comment: Open link in new window
  type:
    hidden: true
  full_width:
    hidden: true

data_config:
  staff_members: true

collections_config:
  pages:
    _enabled_editors:
      - visual
      - content
  staff_members:
    path: data/staff_members
    icon: people
